USE gbs_test;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(64) NOT NULL,
  email VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  status VARCHAR(32) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS txn_tbl (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  note VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS types (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  c_int INT NOT NULL,
  c_big BIGINT NOT NULL,
  c_varchar VARCHAR(255) NOT NULL,
  c_text TEXT,
  c_json JSON,
  c_decimal DECIMAL(10,2) NOT NULL,
  c_bool TINYINT(1) NOT NULL,
  c_blob BLOB,
  c_date DATE,
  c_time TIME,
  c_ts TIMESTAMP NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

USE gbs_filter;

CREATE TABLE IF NOT EXISTS allow_table (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  note VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS deny_table (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  note VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

USE gbs_reserved;

CREATE TABLE IF NOT EXISTS `order` (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  note VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `user-log` (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  note VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
