USE gbs_test;

CREATE TABLE IF NOT EXISTS ddl_tbl (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  note VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE ddl_tbl ADD COLUMN extra VARCHAR(64) NULL;

DROP TABLE ddl_tbl;
