CREATE DATABASE IF NOT EXISTS gbs_cross;
CREATE TABLE IF NOT EXISTS gbs_cross.cross_tbl (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  note VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT INTO gbs_cross.cross_tbl (note) VALUES ("cross-1");
