USE gbs_filter;

CREATE TABLE IF NOT EXISTS ddl_filtered (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  note VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE ddl_filtered ADD COLUMN extra VARCHAR(64) NULL;

DROP TABLE ddl_filtered;
